package com.androidworks.nikhil.whereisitanyam.utils;

/**
 * Created by Nikhil on 25-Sep-16.
 */
public interface Constants {

    String SHARED_PREF_COUNTRIES = "SHARED_PREF_COUNTRIES";
    String SHARED_PREF_TIMEZONES = "SHARED_PREF_TIMEZONES";
    String SHARED_PREF_TUTORIAL_DONE = "SHARED_PREF_TUTORIAL_DONE";
    String SHARED_PREF_ICON_NEEDED = "SHARED_PREF_ICON_NEEDED";
    String SHARED_PREF_VERSION_NUMBER = "SHARED_PREF_VERSION_NUMBER";
    String SELECTED_HOUR = "SELECTED_HOUR";
    String SELECTED_MINUTE = "SELECTED_MINUTE";
}

